name: StatusNamePlugin
version: '1.0'
main: de.unvii.statusNamePlugin.StatusNamePlugin
api-version: '1.21'
authors: [ UnVii ]
description: This plugin is used to set the status shown in the name.
commands:
  status:
    usage: /status set <status> or /status clear
    description: Set your status
    permissions:
      statusnameplugin.use: false
      statusnameplugin.createStatus: true
      statusnameplugin.removeStatus: true